- name: Build
        run: npm run build
        env:
          # GitHub Secrets에 저장된 값을 빌드 시점에 환경 변수로 주입
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_ACCESS_TOKEN: ${{ secrets.VITE_ACCESS_TOKEN }}
          VITE_TMDB_IMG_URL: ${{ secrets.VITE_TMDB_IMG_URL }}
